version: "3"
services:
  go-template:
    build:
      context: .
      dockerfile: Dockerfile
    image: go-template:v1.0
    container_name: go-template
    command: []
    restart: unless-stopped
    ports:
      - "8080:8080"
